### ISSUE TITLE
Unable to reorder scenes in the navigation bar

### ISSUE THREAD

**Issue by AmazingVanish** [ironmonk88/monks-scene-navigation#37] opened 2022-09-07 17:45 UTC
With version 1.0.27 on Foundry VTT 10.284 with DnD5e 2.0.2 I am unable to reorder the scenes in the navigation bar. I have tried on MacOS and Windows 11, bother using browsers (Brave, Chrome. Firefox, Safari) and the app. No other modules installed (except one for The Forge in the browser). Scenes are at the root level, not in a folder. Some relevant screenshots:

![CleanShot 2022-09-07 at 12 22 18](https://user-images.githubusercontent.com/192720/188944396-4e1c6d02-b3d8-41a6-8071-565c55130f44.png)
![CleanShot 2022-09-07 at 12 23 28](https://user-images.githubusercontent.com/192720/188944418-3d2095fb-a26b-4d0d-8515-12fe910a0d87.png)
![CleanShot 2022-09-07 at 12 23 46](https://user-images.githubusercontent.com/192720/188944433-1aae6d6c-bc5a-48b6-80e6-682465cbdb9a.png)

Let me know what other information you might need or things you want me to try.

**Comment by Vallant85** [comment] 2022-09-27 17:02
Also having this issue

**Comment by TiloBuechsenschuss** [comment] 2022-10-03 13:51
I've got the same issue.
Maybe one cool feature to bypass this: automatically order scenes. Either like in the scene browser, or alphabetically.

**Comment by ianm32** [comment] 2022-10-05 02:26
Also experiencing this issue.  Looking at the console while attempting to reorder items shows this:
![image](https://user-images.githubusercontent.com/27756065/193966181-4cb22aa6-0765-4d86-aa98-6d04ac1b97a9.png)

**Comment by MagicOriole** [comment] 2022-10-05 15:46
Confirmed happening to me as well

**Comment by Doresain** [comment] 2022-10-10 00:17
I'm 99% sure this is because of the drag/drop functions in v10 switching to uuid over id and the drop/drop handler here not being updated yet.

I messed around with it a bit and git it partially working (dragging left works, dragging right still doesn't) but I just don't understand drag/drop handling well enough to get it all the way there.

**Comment by ironmonk88** [comment] 2022-10-10 17:18
Should be fixed in the latest release.

**Closed by ironmonk88** 2022-10-10 17:18 UTC
